server:
  port: 9000
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: micro-usuarios
          uri: lb://usuarios
          predicates:
            - Path=/usuarios/**
        - id: micro-pizza-read
          uri: lb://pizza-read
          predicates:
            - Path=/pizza-read/**
        - id: micro-pizza-write
          uri: lb://pizza-write
          predicates:
            - Path=/pizza-write/**