global:
  scrape_interval: 5s

scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: ["172.17.0.1:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # IP de casa Wi-Fi: 192.168.1.41, IP de oficina Wi-Fi: 172.19.4.208
  # Comando "ipconfig" en windows
  - job_name: "usuarios"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["192.168.1.41:8083"]

  - job_name: "pizza-read"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["192.168.1.41:8084"]

  - job_name: "pizza-write"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ "192.168.1.41:8085" ]